from setuptools import setup, find_packages

setup(
    name="intellifold",
    python_requires=">=3.10",
    version="2.0.2",
    packages=find_packages(include=["intellifold", "intellifold.*", "runner"]),
    description="IntelliFold: A Controllable Foundation Model for General and Specialized Biomolecular Structure Prediction.",
    author="IntelliGen AI",
    author_email="contact@intfold.com",
    url="https://github.com/IntelliGen-AI/IntelliFold",
    install_requires = [
        "accelerate==1.1.1",
        "biopython==1.85",
        "click==8.1.8",
        "deepspeed==0.16.4",
        "einops==0.8.0",
        "einx==0.3.0",
        "ihm==2.5",
        "mashumaro==3.14",
        "ml_collections==1.0.0",
        "modelcif==1.2",
        "networkx==3.4.2",
        "numba==0.61.0",
        "numpy==1.24.0",
        "pandas==2.2.3",
        "PyYAML==6.0.2",
        "rdkit==2024.3.2",
        "requests==2.32.3",
        "scipy==1.14.1",
        "torch==2.7.1",
        "torchdiffeq==0.2.5",
        "tqdm==4.67.1",
    ],
    include_package_data=True,
    package_data={
        "intellifold": ["openfold/utils/layer_norm/kernel/*"],
    },
    license="Apache 2.0 License",
    platforms="manylinux1",
    entry_points={
        "console_scripts": [
            "intellifold = runner.intellifold_inference:intellifold_cli",
        ],
    },
)