from setuptools import setup, find_packages

setup(
    name="intellifold",
    python_requires=">=3.10",
    version="2.0.2",
    packages=find_packages(include=["intellifold", "intellifold.*", "runner"]),
    description="IntelliFold: A Controllable Foundation Model for General and Specialized Biomolecular Structure Prediction.",
    author="IntelliGen AI",
    author_email="contact@intfold.com",
    url="https://github.com/IntelliGen-AI/IntelliFold",
    install_requires = [
        "accelerate==1.14.0",
        "biopython==1.85",
        "click==8.4.1",
        "deepspeed==0.17.5",
        "einops==0.8.2",
        "einx==0.4.3",
        "ihm==2.11",
        "mashumaro==3.22",
        "ml_collections==1.1.0",
        "modelcif==1.4",
        "networkx==3.6.1",
        "numba==0.65.1",
        "numpy==1.26.4",
        "pandas==2.3.1",
        "PyYAML==6.0.2",
        "rdkit==2025.9.3",
        "requests==2.34.2",
        "scipy==1.17.1",
        "torch==2.7.1",
        "torchdiffeq==0.2.5",
        "tqdm==4.67.1",
    ],
    include_package_data=True,
    package_data={
        "intellifold": ["openfold/utils/layer_norm/kernel/*"],
    },
    license="Apache 2.0 License",
    platforms="manylinux1",
    entry_points={
        "console_scripts": [
            "intellifold = runner.intellifold_inference:intellifold_cli",
        ],
    },
)